/*
 * ordinal_table.c — Ordinal import name lookup
 *
 * Static lookup table mapping (DLL name, ordinal) → function name.
 * Covers common ordinals for Windows 10/11 x64 ntdll, kernel32, and msvcrt.
 */

#include <stdint.h>
#include <string.h>
#include "include/syscall_safe_utils.h"

typedef struct {
    const char *dll_name;
    uint16_t ordinal;
    const char *func_name;
} ordinal_entry_t;

static const ordinal_entry_t ordinal_table[] = {
    /* ntdll.dll ordinals (Windows 10/11 x64) */
    { "ntdll.dll", 1,  "NtAccessCheck" },
    { "ntdll.dll", 5,  "NtCallbackReturn" },
    { "ntdll.dll", 7,  "NtQueryInformationProcess" },
    { "ntdll.dll", 9,  "NtCreateDebugObject" },
    { "ntdll.dll", 11, "NtSuspendThread" },
    { "ntdll.dll", 12, "NtResumeThread" },
    { "ntdll.dll", 14, "NtQuerySystemTime" },
    { "ntdll.dll", 17, "NtEnumerateValueKey" },
    { "ntdll.dll", 18, "NtEnumerateSystemEnvironmentValuesEx" },
    { "ntdll.dll", 19, "NtClose" },
    { "ntdll.dll", 20, "NtQueryDefaultLocale" },
    { "ntdll.dll", 21, "NtQueryValueKey" },
    { "ntdll.dll", 24, "NtQueryInformationThread" },
    { "ntdll.dll", 26, "NtDelayExecution" },
    { "ntdll.dll", 29, "NtTerminateThread" },
    { "ntdll.dll", 31, "NtRaiseException" },
    { "ntdll.dll", 37, "NtSetInformationFile" },
    { "ntdll.dll", 40, "NtQueryInformationFile" },
    { "ntdll.dll", 41, "NtFlushBuffersFile" },
    { "ntdll.dll", 45, "NtPulseEvent" },
    { "ntdll.dll", 46, "NtSetTimer" },
    { "ntdll.dll", 48, "NtMapViewOfSection" },
    { "ntdll.dll", 49, "NtUnmapViewOfSection" },
    { "ntdll.dll", 52, "NtAllocateVirtualMemory" },
    { "ntdll.dll", 56, "NtWriteVirtualMemory" },
    { "ntdll.dll", 57, "NtWriteFile" },
    { "ntdll.dll", 58, "NtDuplicateObject" },
    { "ntdll.dll", 59, "NtQueryAttributesFile" },
    { "ntdll.dll", 60, "NtClearEvent" },
    { "ntdll.dll", 61, "NtReadVirtualMemory" },
    { "ntdll.dll", 63, "NtReleaseSemaphore" },
    { "ntdll.dll", 65, "NtOpenProcess" },
    { "ntdll.dll", 66, "NtOpenThread" },
    { "ntdll.dll", 68, "NtCreateMutex" },
    { "ntdll.dll", 71, "NtCreateSection" },
    { "ntdll.dll", 73, "NtFlushBuffersFile" },
    { "ntdll.dll", 75, "NtCreateProcess" },
    { "ntdll.dll", 76, "NtCreateSemaphore" },
    { "ntdll.dll", 77, "NtCreateTimer" },
    { "ntdll.dll", 78, "NtProtectVirtualMemory" },
    { "ntdll.dll", 82, "NtLockVirtualMemory" },
    { "ntdll.dll", 84, "NtQueryEvent" },
    { "ntdll.dll", 85, "NtQueryPerformanceCounter" },
    { "ntdll.dll", 86, "NtQueryPerformanceFrequency" },
    { "ntdll.dll", 87, "NtQueryVolumeInformationFile" },
    { "ntdll.dll", 88, "NtWaitForMultipleObjects" },
    { "ntdll.dll", 89, "NtCreateFile" },
    { "ntdll.dll", 90, "NtQueryFullAttributesFile" },
    { "ntdll.dll", 91, "NtCancelIoFile" },
    { "ntdll.dll", 92, "NtSetEvent" },
    { "ntdll.dll", 94, "NtResetEvent" },
    { "ntdll.dll", 95, "NtCancelTimer" },
    { "ntdll.dll", 97, "NtSignalAndWaitForSingleObject" },
    { "ntdll.dll", 99, "NtOpenKey" },
    { "ntdll.dll", 100, "NtQueryDirectoryFile" },
    { "ntdll.dll", 101, "NtUnlockVirtualMemory" },
    { "ntdll.dll", 102, "NtQueryVirtualMemory" },
    { "ntdll.dll", 105, "NtSetSystemTime" },
    { "ntdll.dll", 107, "NtSetValueKey" },
    { "ntdll.dll", 108, "NtCreateKey" },
    { "ntdll.dll", 109, "NtDeleteKey" },
    { "ntdll.dll", 111, "NtDeleteValueKey" },
    { "ntdll.dll", 113, "NtCreateKeyedEvent" },
    { "ntdll.dll", 115, "NtCreateNamedPipeFile" },
    { "ntdll.dll", 116, "NtCreatePagingFile" },
    { "ntdll.dll", 119, "NtCreateThread" },
    { "ntdll.dll", 122, "NtNotifyChangeDirectoryFile" },
    { "ntdll.dll", 123, "NtNotifyChangeKey" },
    { "ntdll.dll", 124, "NtOpenFile" },
    { "ntdll.dll", 127, "NtCreateEvent" },
    { "ntdll.dll", 128, "NtCreateThreadEx" },
    { "ntdll.dll", 129, "NtWaitForSingleObject" },
    { "ntdll.dll", 130, "NtQueryInformationFile" },
    { "ntdll.dll", 132, "NtQueryOpenSubKeys" },
    { "ntdll.dll", 133, "NtQueryOpenSubKeysEx" },
    { "ntdll.dll", 134, "NtReleaseMutant" },
    /* kernel32.dll ordinals (subset) */
    { "kernel32.dll", 2,  "GetVersion" },
    { "kernel32.dll", 6,  "GetStdHandle" },
    { "kernel32.dll", 7,  "InterlockedExchange" },
    { "kernel32.dll", 10, "GetTickCount" },
    { "kernel32.dll", 15, "GetCommandLineA" },
    { "kernel32.dll", 17, "WriteFile" },
    { "kernel32.dll", 18, "GetFileType" },
    { "kernel32.dll", 19, "ReadFile" },
    { "kernel32.dll", 21, "SetLastError" },
    { "kernel32.dll", 30, "GetCommandLineW" },
    { "kernel32.dll", 32, "GetStartupInfoA" },
    { "kernel32.dll", 33, "GetStartupInfoW" },
    { "kernel32.dll", 34, "GetModuleHandleA" },
    { "kernel32.dll", 35, "GetModuleHandleW" },
    { "kernel32.dll", 37, "ExitProcess" },
    { "kernel32.dll", 38, "GetVersionExA" },
    { "kernel32.dll", 39, "SetUnhandledExceptionFilter" },
    { "kernel32.dll", 42, "CreateFileA" },
    { "kernel32.dll", 43, "CloseHandle" },
    { "kernel32.dll", 44, "GetModuleFileNameA" },
    { "kernel32.dll", 48, "GetModuleFileNameW" },
    { "kernel32.dll", 50, "GetFileAttributesA" },
    { "kernel32.dll", 51, "GetFileAttributesW" },
    { "kernel32.dll", 60, "GetFileAttributesExA" },
    { "kernel32.dll", 64, "GetTickCount64" },
    { "kernel32.dll", 78, "GetEnvironmentStrings" },
    { "kernel32.dll", 100, "FreeLibrary" },
    { "kernel32.dll", 113, "GetProcAddress" },
    { "kernel32.dll", 125, "LoadLibraryA" },
    { "kernel32.dll", 126, "LoadLibraryW" },
    { "kernel32.dll", 134, "LoadLibraryExA" },
    { "kernel32.dll", 135, "LoadLibraryExW" },
    { "kernel32.dll", 147, "TlsAlloc" },
    { "kernel32.dll", 148, "TlsGetValue" },
    { "kernel32.dll", 149, "TlsSetValue" },
    { "kernel32.dll", 150, "TlsFree" },
    { "kernel32.dll", 169, "EnterCriticalSection" },
    { "kernel32.dll", 170, "InitializeCriticalSection" },
    { "kernel32.dll", 171, "LeaveCriticalSection" },
    { "kernel32.dll", 172, "DeleteCriticalSection" },
    { "kernel32.dll", 190, "GetLastError" },
    { "kernel32.dll", 191, "GetSystemTime" },
    { "kernel32.dll", 192, "GetSystemTimeAsFileTime" },
    { "kernel32.dll", 193, "Sleep" },
    { "kernel32.dll", 194, "QueryPerformanceCounter" },
    { "kernel32.dll", 195, "QueryPerformanceFrequency" },
    { "kernel32.dll", 200, "CreateMutexA" },
    { "kernel32.dll", 201, "CreateMutexW" },
    { "kernel32.dll", 202, "ReleaseMutex" },
    { "kernel32.dll", 231, "CreateFileW" },
    { "kernel32.dll", 237, "CreateFileMappingA" },
    { "kernel32.dll", 263, "CreateEventA" },
    { "kernel32.dll", 264, "CreateEventW" },
    { "kernel32.dll", 265, "SetEvent" },
    { "kernel32.dll", 266, "ResetEvent" },
    { "kernel32.dll", 268, "WaitForSingleObject" },
    { "kernel32.dll", 270, "WaitForMultipleObjects" },
    { "kernel32.dll", 289, "VirtualProtect" },
    { "kernel32.dll", 290, "VirtualAlloc" },
    { "kernel32.dll", 291, "VirtualFree" },
    { "kernel32.dll", 292, "VirtualQuery" },
    { "kernel32.dll", 293, "VirtualQueryEx" },
    { "kernel32.dll", 296, "HeapAlloc" },
    { "kernel32.dll", 297, "HeapCreate" },
    { "kernel32.dll", 298, "HeapFree" },
    { "kernel32.dll", 299, "HeapReAlloc" },
    { "kernel32.dll", 300, "HeapSize" },
    { "kernel32.dll", 301, "HeapWalk" },
    { "kernel32.dll", 302, "GetProcessHeap" },
    { "kernel32.dll", 303, "HeapDestroy" },
    { "kernel32.dll", 304, "GetProcessHeaps" },
    /* msvcrt.dll ordinals (subset) */
    { "msvcrt.dll", 1,  "abort" },
    { "msvcrt.dll", 5,  "_amsg_exit" },
    { "msvcrt.dll", 14, "_commode" },
    { "msvcrt.dll", 15, "_fmode" },
    { "msvcrt.dll", 20, "calloc" },
    { "msvcrt.dll", 26, "exit" },
    { "msvcrt.dll", 34, "fprintf" },
    { "msvcrt.dll", 35, "free" },
    { "msvcrt.dll", 36, "fwrite" },
    { "msvcrt.dll", 42, "malloc" },
    { "msvcrt.dll", 43, "memcpy" },
    { "msvcrt.dll", 57, "signal" },
    { "msvcrt.dll", 58, "sleep" },
    { "msvcrt.dll", 65, "strlen" },
    { "msvcrt.dll", 66, "strncmp" },
    { "msvcrt.dll", 67, "strcmp" },
    { "msvcrt.dll", 68, "strcpy" },
    { "msvcrt.dll", 69, "strncpy" },
    { "msvcrt.dll", 77, "vfprintf" },
    { "msvcrt.dll", 78, "sprintf" },
    { "msvcrt.dll", 84, "vsprintf" },
    { NULL, 0, NULL }
};

/* Look up a function name by DLL + ordinal. Returns NULL if not found. */
const char *ordinal_lookup(const char *dll_name, uint16_t ordinal)
{
    for (int i = 0; ordinal_table[i].dll_name != NULL; i++) {
        if (syscall_safe_strcasecmp(ordinal_table[i].dll_name, dll_name) == 0 &&
            ordinal_table[i].ordinal == ordinal) {
            return ordinal_table[i].func_name;
        }
    }
    return NULL;
}
