/*
 * crt_offset_discovery.c — CRT offset discovery
 *
 * Discover CRT global variable offsets (argc/argv/envp) via COFF symbol
 * table lookup or .text instruction scanning.
 *
 * =====================================================================
 * TOOLCHAIN NOTE: mingw-w64 ONLY
 * =====================================================================
 *
 * This code assumes the target PE was compiled with mingw-w64 (GNU C
 * runtime for Windows).  The CRT BSS layout (__argc, __argv, __initenv)
 * and the .refptr instruction patterns it scans for are specific to
 * mingw-w64.  PEs built with MSVC, LLVM/Clang (clang-cl), or other
 * toolchains will have different CRT layouts and this discovery will
 * fail or produce incorrect offsets.
 * =====================================================================
 */

#define _GNU_SOURCE

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

#include "include/common.h"
#include "include/crt.h"
#include "include/pe_parser.h"
#include "include/pe_priv.h"
#include "msvcrt_priv.h"
#include "include/debug.h"

/* Auto-generated CRT offsets from build-time toolchain analysis.
 * If this header exists (generated by scripts/gen_crt_offsets.sh), use
 * its offsets as the fallback instead of the hardcoded common.h values. */
#ifdef HAVE_GENERATED_CRT_OFFSETS
#include "include/crt_offsets_generated.h"
#endif

/*
 * Scan .text for the pattern:
 *   mov reg64, [rip + disp32]
 *   mov reg64, [reg64]
 *
 * This two-level indirection is the signature of a .refptr usage.
 * We collect all such target addresses and try to match them against
 * known CRT symbols by checking their current values.
 */
void scan_text_for_refptrs(void *image_base, IMAGE_NT_HEADERS *nt,
                           IMAGE_SECTION_HEADER *sections,
                           uint64_t image_size, void *initenv_stub)
{
    IMAGE_SECTION_HEADER *text_sec = find_section_by_name(nt, sections, ".text");
    if (!text_sec) {
        DEBUG("crt_offset_discovery: no .text section");
        return;
    }

    uint64_t text_vaddr = text_sec->VirtualAddress;
    uint64_t text_size = text_sec->Misc.VirtualSize;
    if (text_size == 0) text_size = text_sec->SizeOfRawData;
    if (text_vaddr > UINT32_MAX || text_size > image_size ||
        text_vaddr > image_size - text_size) {
        return;
    }
    uint8_t *text_base = pe_rva_to_ptr(image_base, nt, (uint32_t)text_vaddr,
                                       (size_t)text_size);
    if (text_base == NULL) {
        return;
    }

    int found = 0;
    for (uint64_t off = 0; off + 7 < text_size; off++) {
        uint8_t *p = text_base + off;

        /* 48 8B 05 disp32 = mov rax, [rip+disp32] */
        if (p[0] != X86_REX_W || p[1] != X86_MOV_R64_RIP || p[2] != X86_MOV_RIP) continue;

        int32_t disp = (int32_t)*((int32_t *)(p + 3));
        uint64_t instr_rva = text_vaddr + off;
        uint64_t target_rva = instr_rva + 7 + disp;

        if (target_rva > UINT32_MAX ||
            !pe_rva_range_is_valid((uint32_t)target_rva, sizeof(uint64_t),
                                   image_size)) {
            continue;
        }
        if (target_rva >= text_vaddr && target_rva < text_vaddr + text_size) continue;

        /* Look forward up to 40 bytes for deref+write pattern:
         *   48 8B 00 (mov rax, [rax])
         *   XX 89 00 or XX C7 00 (write to [rax])
         * This distinguishes __imp___initenv (deref+write) from callbacks (deref+test+call). */
        int has_write_deref = 0;
        for (uint64_t d = 7; d + 4 < 40 && d + 4 < text_size - off; d++) {
            if (p[d] == X86_REX_W && p[d+1] == X86_MOV_R64_RIP && p[d+2] == X86_MOV_RAX_RAX) {
                /* Found deref. Check if next is a store to [rax].
                 * Store patterns: 89 XX, C7 XX, 48 89 XX, 4C 89 XX where XX has mod=00,rm=00 */
                uint64_t nd = d + 3;
                if (nd + 2 < 40 && nd + 2 < text_size - off) {
                    /* Check for store to [rax] after deref.
                     * Patterns: 89 00, C7 00, or with REX prefix: 48/4C/4D/49 89 00 */
                    uint8_t a = p[nd], b = p[nd+1], c = p[nd+2];
                    int is_store = 0;
                    if (a == X86_MOV_RM_R64 && b == X86_MOV_RAX_RAX) is_store = 1;           /* 89 00 */
                    if (a == X86_MOV_RM_IMM && b == X86_MOV_RAX_RAX) is_store = 1;           /* C7 00 */
                    if ((a & 0xF0) == 0x40 && b == X86_MOV_RM_R64 && c == X86_MOV_RAX_RAX)   /* REX 89 00 */
                        is_store = 1;
                    if ((a & 0xF0) == 0x40 && b == X86_MOV_RM_IMM && c == X86_MOV_RAX_RAX)   /* REX C7 00 */
                        is_store = 1;
                    if (is_store) {
                        has_write_deref = 1;
                        break;
                    }
                }
                break;  /* No write after deref — not __imp___initenv */
            }
        }

        if (!has_write_deref) continue;

        /* Found refptr target at target_rva. Check if in a data section. */
        uint64_t *target_ptr = pe_rva_to_ptr(image_base, nt,
                                             (uint32_t)target_rva,
                                             sizeof(uint64_t));
        if (target_ptr == NULL) continue;
        uint64_t current = *target_ptr;
        int in_data_section = 0;
        const char *sec_name = "unknown";
        for (uint16_t si = 0; si < pe_section_count(nt); si++) {
            IMAGE_SECTION_HEADER *sec = &sections[si];
            if (sec == text_sec) continue;
            uint64_t sec_size = sec->Misc.VirtualSize > 0
                                ? sec->Misc.VirtualSize
                                : sec->SizeOfRawData;
            if (sec_size > UINT32_MAX - sec->VirtualAddress)
                continue;
            uint64_t sec_end = sec->VirtualAddress + sec_size;
            if (target_rva >= sec->VirtualAddress && target_rva < sec_end) {
                sec_name = (const char *)sec->Name;
                if ((target_rva - sec->VirtualAddress) % 8 == 0) {
                    in_data_section = 1;
                }
                break;
            }
        }
        DEBUG("crt_offset_discovery: text-scan refptr at rva 0x%lx val=0x%lx in '%s' data=%d",
                (unsigned long)target_rva, current, sec_name, in_data_section);

        if (!in_data_section) continue;

        /* Patch refptr targets that point to PE-internal addresses
         * (they likely point to IAT entries or other host-addr data) */
        if (initenv_stub != NULL) {
            /* Patch to the passed stub — the CRT will deref to get .bss+0x18 */
            apply_refptr_patch(image_base, target_rva,
                               initenv_stub,
                               "__imp___initenv (text-scan)", image_size,
                               (uint64_t)(uintptr_t)image_base, 0,
                               nt, sections);
            found = 1;
        }
    }

    if (!found)
        DEBUG("crt_offset_discovery: text-scan found no refptr targets");
}

/*
 * Opens the PE file, mmaps it, and extracts the symbol table + string table.
 * Returns 0 on success, -1 on failure.
 * On success: sets *out_file_map, *out_symbols, *out_string_table, *out_file_size.
 * Caller must munmap(*out_file_map, *out_file_size) when done.
 */
static int open_and_map_symbols(
    const char *file_path,
    IMAGE_NT_HEADERS *nt,
    void **out_file_map,
    IMAGE_SYMBOL **out_symbols,
    char **out_string_table,
    size_t *out_file_size)
{
    uint32_t sym_ptr = pe_pointer_to_symbol_table(nt);
    uint32_t sym_count = pe_number_of_symbols(nt);

    if (sym_ptr == 0 || sym_count == 0)
        return -1;

    int fd = open(file_path, O_RDONLY);
    if (fd < 0) return -1;

    struct stat st;
    if (fstat(fd, &st) < 0) { close(fd); return -1; }

    void *file_map = mmap(NULL, st.st_size, PROT_READ, MAP_PRIVATE, fd, 0);
    close(fd);
    if (file_map == MAP_FAILED) return -1;

    size_t sym_table_size = (size_t)sym_count * IMAGE_SIZEOF_SYMBOL;
    if (sym_count != 0 && sym_table_size / IMAGE_SIZEOF_SYMBOL != sym_count) {
        munmap(file_map, st.st_size);
        return -1;
    }

    IMAGE_SYMBOL *symbols = (IMAGE_SYMBOL *)safe_ptr_at(file_map, sym_ptr,
                                                        sym_table_size,
                                                        (size_t)st.st_size);
    if (symbols == NULL) {
        munmap(file_map, st.st_size);
        return -1;
    }

    char *string_table = NULL;
    size_t str_off = sym_ptr + sym_table_size;
    if ((size_t)st.st_size >= sizeof(uint32_t) &&
        str_off >= sym_ptr &&
        str_off <= (size_t)st.st_size - sizeof(uint32_t)) {
        const uint32_t *str_size_ptr = safe_ptr_at(file_map, str_off,
                                                   sizeof(uint32_t),
                                                   (size_t)st.st_size);
        if (str_size_ptr == NULL) {
            munmap(file_map, st.st_size);
            return -1;
        }
        uint32_t str_size = *str_size_ptr;
        /* Allow small overhang (up to 64 bytes) for string table that extends
         * past the file. Some PE tools include padding in the size field. */
        size_t str_end = str_off + 4 + str_size;
        if (str_end >= str_off && str_end <= (size_t)st.st_size + 64 && str_size > 0) {
            string_table = (char *)file_map + str_off + 4;
        }
    }

    *out_file_map = file_map;
    *out_file_size = (size_t)st.st_size;
    *out_symbols = symbols;
    *out_string_table = string_table;
    return 0;
}

/*
 * Convert a section-bound symbol to its RVA.
 * Returns the RVA or 0 if the symbol can't be converted.
 */
static uint64_t compute_rva_from_symbol(
    const IMAGE_SYMBOL *sym, IMAGE_NT_HEADERS *nt,
    IMAGE_SECTION_HEADER *sections)
{
    int32_t section_num = sym->SectionNumber;

    if (section_num > 0 && (size_t)section_num <= pe_section_count(nt)) {
        IMAGE_SECTION_HEADER *sec = &sections[section_num - 1];
        if (sym->Value > UINT32_MAX - sec->VirtualAddress)
            return 0;
        return sec->VirtualAddress + sym->Value;
    }
    if (section_num == 0) {
        return sym->Value;
    }
    return 0;
}

/*
 * Try to match a single symbol name against the target using 4 strategies:
 * .rdata$.refptr. prefix, .refptr. prefix, exact match, substring fallback.
 * Returns 1 if matched, 0 otherwise.
 */
static int match_symbol_name(const char *sym_name, size_t sym_name_len,
                             const char *name)
{
    /* Strategy 1: .rdata$.refptr.<name> */
    {
        const char *prefix = ".rdata$.refptr.";
        size_t plen = strlen(prefix);
        if (sym_name_len == plen + strlen(name) &&
            strncmp(sym_name, prefix, plen) == 0 &&
            strncmp(sym_name + plen, name, sym_name_len - plen) == 0)
            return 1;
    }

    /* Strategy 2: .refptr.<name> */
    {
        const char *prefix = ".refptr.";
        size_t plen = strlen(prefix);
        if (sym_name_len == plen + strlen(name) &&
            strncmp(sym_name, prefix, plen) == 0 &&
            strncmp(sym_name + plen, name, sym_name_len - plen) == 0)
            return 1;
    }

    /* Strategy 3: exact name match */
    if (strncmp(sym_name, name, sym_name_len) == 0 &&
        name[sym_name_len] == '\0')
        return 1;

    /* Strategy 4: substring fallback */
    if (sym_name_len > 8 && strstr(sym_name, name) != NULL) {
        if (strncmp(name, "__CTOR_LIST__", 13) == 0 || strncmp(name, "__DTOR_LIST__", 13) == 0) {
            DEBUG_LEVEL(3, "DBG_COFF_SUB: '%.*s' matched '%s' as substring",
                    (int)sym_name_len, sym_name, name);
        }
        return 1;
    }

    return 0;
}

/*
 * Search the symbol table for a symbol matching the target name.
 * Tries (in order): .rdata$.refptr. prefix, .refptr. prefix, exact match, substring.
 * Prefers section-bound symbols over absolute.
 * Returns index of the best matching symbol, or -1 if not found.
 * Sets *out_best_rva to the RVA of the best match.
 */
static int find_matching_symbol(
    IMAGE_SYMBOL *symbols, char *string_table, uint32_t sym_count,
    const char *name,
    IMAGE_NT_HEADERS *nt, IMAGE_SECTION_HEADER *sections,
    uint64_t *out_best_rva)
{
    uint64_t best_rva = 0;
    int best_idx = -1;
    int has_section_match = 0;

    /*
     * Scan all symbols, preferring section-bound over absolute.
     * Some mingw-w64 builds have garbage absolute symbols (sec=0) with
     * wrong values that appear before the real section-bound entry.
     */
    DEBUG_LEVEL(3, "DBG_COFF: '%s' scanning %u symbols", name, sym_count);
    for (uint32_t i = 0; i < sym_count; i++) {
        const IMAGE_SYMBOL *sym = &symbols[i];
        const char *sym_name = get_symbol_name(sym, string_table);
        if (!sym_name) continue;
        size_t sym_name_len = strlen(sym_name);

        if (i < 3) {
            DEBUG_LEVEL(3, "DBG_COFF: sym[%u] = '%.*s' sect=%d",
                    i, (int)sym_name_len, sym_name, sym->SectionNumber);
        }

        /* Debug: show all symbols containing CTOR or DTOR */
        if (strstr(sym_name, "CTOR") || strstr(sym_name, "DTOR")) {
            DEBUG_LEVEL(3, "DBG_COFF_SYM: idx=%u name='%.*s' sect=%d val=%u type=%d",
                    i, (int)sym_name_len, sym_name, (int)sym->SectionNumber, sym->Value, sym->Type);
        }

        int matched = match_symbol_name(sym_name, sym_name_len, name);

        if (!matched) continue;

        if (strncmp(name, "__CTOR_LIST__", 13) == 0 || strncmp(name, "__DTOR_LIST__", 13) == 0) {
            DEBUG_LEVEL(3, "DBG_COFF_MATCH: sym[%u] '%.*s' sect=%d val=%u num_secs=%u has=%d",
                    i, (int)sym_name_len, sym_name, sym->SectionNumber, sym->Value,
                    pe_section_count(nt), has_section_match);
        }

        int32_t section_num = sym->SectionNumber;

        /* Prefer section-bound symbols. If we already have one, skip.
         * For absolute symbols (sec=0), remember as fallback only. */
        if (section_num > 0 && (size_t)section_num <=
            pe_section_count(nt)) {
            if (!has_section_match) {
                best_rva = compute_rva_from_symbol(sym, nt, sections);
                best_idx = i;
                has_section_match = 1;
            }
        } else if (section_num == 0 && !has_section_match) {
            /* Fallback: absolute symbol, but only if no section-bound one */
            best_rva = compute_rva_from_symbol(sym, nt, sections);
            best_idx = i;
        }
    }

    *out_best_rva = best_rva;
    return best_idx;
}

/*
 * Read the COFF symbol table from the PE file to find symbol addresses.
 * Returns the RVA (relative virtual address) of the symbol, or 0 if not found.
 */
uint64_t find_symbol_rva_from_file(const char *file_path,
                                   IMAGE_NT_HEADERS *nt,
                                   IMAGE_SECTION_HEADER *sections,
                                   const char *name)
{
    uint32_t sym_count = pe_number_of_symbols(nt);

    void *file_map;
    size_t file_size;
    IMAGE_SYMBOL *symbols;
    char *string_table;

    if (open_and_map_symbols(file_path, nt, &file_map, &symbols,
                             &string_table, &file_size) != 0)
        return 0;

    uint64_t best_rva;
    (void)find_matching_symbol(symbols, string_table, sym_count, name,
                               nt, sections, &best_rva);

    DEBUG_LEVEL(3, "DBG_COFF: '%s' -> rva=0x%lx", name, (unsigned long)best_rva);
    munmap(file_map, file_size);
    return best_rva;
}

/*
 * Discover CRT global variable offsets (argc/argv/envp) from COFF symbol table.
 * Sets ctx->argc_bss_offset, ctx->argv_bss_offset, ctx->envp_bss_offset.
 * Falls back to hardcoded offsets if COFF lookup is incomplete.
 * Accepts ctx parameter instead of reading g_crt_ctx directly for reentrancy.
 */
void discover_crt_offsets(const char *file_path,
                          IMAGE_NT_HEADERS *nt,
                          IMAGE_SECTION_HEADER *sections,
                          crt_context_t *ctx)
{
    ctx->argc_bss_offset = 0;
    ctx->argv_bss_offset = 0;
    ctx->envp_bss_offset = 0;

    const char *crt_sym_names[][2] = {
        { "_argc", "__argc" },
        { "_argv", "__argv" },
        { "_environ", "__envp" },
    };
    uint32_t *offset_targets[3] = {
        &ctx->argc_bss_offset,
        &ctx->argv_bss_offset,
        &ctx->envp_bss_offset,
    };

    for (int ci = 0; ci < 3; ci++) {
        for (int ni = 0; ni < 2; ni++) {
            uint64_t rva = find_symbol_rva_from_file(file_path, nt, sections, crt_sym_names[ci][ni]);
            if (rva != 0) {
                uint32_t off = (uint32_t)(rva - ctx->bss_vaddr);
                *offset_targets[ci] = off;
                break;
            }
        }
    }

    /* Fallback: if COFF lookup failed, try CRT module accessor, then hardcoded */
    if (ctx->argc_bss_offset == 0 || ctx->argv_bss_offset == 0 || ctx->envp_bss_offset == 0) {
        const crt_module_t *mod = crt_get_module(CRT_TYPE_MINGW);
        if (mod && crt_bss_init_offset(mod)) {
            DEBUG_LEVEL(1, "WARNING: COFF symbol lookup for argc/argv/envp incomplete, "
                  "using CRT module fallback (0x%x/0x%x/0x%x)",
                  crt_bss_initenv_offset(mod), crt_bss_argv_offset(mod),
                  crt_bss_init_offset(mod));
            if (ctx->argc_bss_offset == 0) ctx->argc_bss_offset = crt_bss_init_offset(mod);
            if (ctx->argv_bss_offset == 0) ctx->argv_bss_offset = crt_bss_argv_offset(mod);
            if (ctx->envp_bss_offset == 0) ctx->envp_bss_offset = crt_bss_initenv_offset(mod);
        } else {
            /* Hardcoded fallback if CRT module isn't available */
            #define FALLBACK_ARGC 0x028
            #define FALLBACK_ARGV 0x020
            #define FALLBACK_INITENV 0x018
            #define FALLBACK_ACMDLN 0x030
            DEBUG_LEVEL(1, "WARNING: COFF symbol lookup for argc/argv/envp incomplete, "
                  "using hardcoded CRT offsets (0x%x/0x%x/0x%x)",
                  FALLBACK_INITENV, FALLBACK_ARGV, FALLBACK_ARGC);
            if (ctx->argc_bss_offset == 0) ctx->argc_bss_offset = FALLBACK_ARGC;
            if (ctx->argv_bss_offset == 0) ctx->argv_bss_offset = FALLBACK_ARGV;
            if (ctx->envp_bss_offset == 0) ctx->envp_bss_offset = FALLBACK_INITENV;
        }
    }

    DEBUG_LEVEL(2, "crt_offset_discovery: CRT offsets argc=0x%x argv=0x%x envp=0x%x",
            ctx->argc_bss_offset, ctx->argv_bss_offset, ctx->envp_bss_offset);
}
